### ISSUE TITLE
Error when trying to execute K command from gulp.js

### ISSUE THREAD

**Issue by spboyer** [spboyer/GulpTypeScript#1]
`gulp.task('run', shell.task(['k web']));`

returns

```
[12:07:57] Using gulpfile ~\GulpTypeScript\src\GulpTypeScript\gulpfile.js
[12:07:57] Starting 'run'...
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Microsoft.Framework.ConfigurationModel.EnvironmentVariablesConfigurationSource.Load(IDictionary envVariables)
   at Microsoft.Framework.ConfigurationModel.EnvironmentVariablesConfigurationSource.Load()
   at Microsoft.Framework.ConfigurationModel.Configuration.Add(IConfigurationSource configurationSource)
   at Microsoft.AspNet.Hosting.Program.Main(String[] args)
[12:07:57] 'run' errored after 715 ms
[12:07:57] Error in plugin 'gulp-shell'
Message:
    Command failed: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Microsoft.Framework.ConfigurationModel.EnvironmentVariablesConfigurationSource.Load(IDictionary envVariables)
   at Microsoft.Framework.ConfigurationModel.EnvironmentVariablesConfigurationSource.Load()
   at Microsoft.Framework.ConfigurationModel.Configuration.Add(IConfigurationSource configurationSource)
   at Microsoft.AspNet.Hosting.Program.Main(String[] args)

Details:
    killed: false
    code: 1
    signal: null
    stdout: 
    stderr: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Microsoft.Framework.ConfigurationModel.EnvironmentVariablesConfigurationSource.Load(IDictionary envVariables)
   at Microsoft.Framework.ConfigurationModel.EnvironmentVariablesConfigurationSource.Load()
   at Microsoft.Framework.ConfigurationModel.Configuration.Add(IConfigurationSource configurationSource)
   at Microsoft.AspNet.Hosting.Program.Main(String[] args)

Process terminated with code 1.
```

however can run `k web` in Windows or `k kestrel` on OSX from command line and it's fine.  

@johnpapa @madskristensen @rustd

**Comment by spboyer** [comment]
Changed to child_process.exec()

```
[14:02:56] Using gulpfile ~\Documents\GitHub\GulpTypeScript\src\GulpTypeScript\g
ulpfile.js
[14:02:56] Starting 'run'...
running...
done...
[14:02:59] 'run' errored after 2.86 s
[14:02:59] Error: Command failed: Microsoft.Net.Http.Server.WebListenerException
 (0x80004005): The prefix 'http://localhost:5001/' is already registered.
   at Microsoft.Net.Http.Server.WebListener.AddAllPrefixes()
   at Microsoft.Net.Http.Server.WebListener.Start()
   at Microsoft.AspNet.Server.WebListener.MessagePump.Start(Func`2 app)
   at Microsoft.AspNet.Server.WebListener.ServerFactory.Start(IServerInformation
 server, Func`2 app)
   at Microsoft.AspNet.Hosting.HostingEngine.Start(HostingContext context)
   at Microsoft.AspNet.Hosting.Program.Main(String[] args)

    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
```
